project_id: '684356'
# api_token_env: CROWDIN_PERSONAL_TOKEN
api_token: '5a187ac5e7a71e03940896f67d3b3480783f0c3ce776663c17e6279e82ac9eb26e0034dbb592d31c' # DELETE AFTER TESTING
preserve_hierarchy: true
files:
  # JSON translation files
  - source: /i18n/en-us/**/**
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  # Docs Markdown files
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  # # Blog Markdown files
  # - source: /blog/**/*
  #   translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
