/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // sidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */

  bairdBeerQuadrants: [
    'baird-beer-quadrants/overview',
    'baird-beer-quadrants/beers-year-round',
    'baird-beer-quadrants/beers-monthly-style-series',
    'baird-beer-quadrants/beers-fruitful-life-series',
    'baird-beer-quadrants/beers-taproom-exclusive',
  ],
  bitcoinCashNodeOnRaspberryPi: [
    'bitcoin-cash-node-on-raspberry-pi/overview',
    {
      'Install and set up': [
        'bitcoin-cash-node-on-raspberry-pi/installation-and-setup/overview',
        'bitcoin-cash-node-on-raspberry-pi/installation-and-setup/preparation',
        'bitcoin-cash-node-on-raspberry-pi/installation-and-setup/bchn-setup',
        'bitcoin-cash-node-on-raspberry-pi/installation-and-setup/wallet-setup',
        'bitcoin-cash-node-on-raspberry-pi/installation-and-setup/conclusion',
        'bitcoin-cash-node-on-raspberry-pi/installation-and-setup/references',
      ],
      'Upgrade': [
        'bitcoin-cash-node-on-raspberry-pi/upgrade/overview',
        'bitcoin-cash-node-on-raspberry-pi/upgrade/preparation',
        'bitcoin-cash-node-on-raspberry-pi/upgrade/bchn-upgrade',
        'bitcoin-cash-node-on-raspberry-pi/upgrade/cleanup',
        'bitcoin-cash-node-on-raspberry-pi/upgrade/conclusion',
      ],
    },
  ],
  zuneSoftwareSetup: [
    'zune-software-setup/overview',
    'zune-software-setup/getting-started',
    'zune-software-setup/installing-the-zune-software',
    'zune-software-setup/connecting-with-the-zune-software',
    'zune-software-setup/adding-apps-and-games',
    'zune-software-setup/conclusion',
    'zune-software-setup/references',
  ],
  passgen: [
    'passgen/overview',
    'passgen/generating-passwords',
    'passgen/updating-the-app',
    'passgen/uninstalling',
    'passgen/references',
  ],
};

export default sidebars;
