name: Add `new feature` label to PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  manage-feature-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR body
        id: pr_body
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Add 'new feature' label if checked
        if: contains(steps.pr_body.outputs.body, '- [x] This PR includes a new feature.') || contains(steps.pr_body.outputs.body, '- [x] This PR includes a new feature.')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: new feature

      - name: Remove 'new feature' label if unchecked
        if: |
          !contains(steps.pr_body.outputs.body, '- [x] This PR includes a new feature.') &&
          !contains(steps.pr_body.outputs.body, '- [x] This PR includes a new feature.')
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: new feature
