# The GitHub personal access token used in this deploy expires on September 1, 2023.
name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install \ 
          "mkdocs-video" \
          "mkdocs-git-revision-date-localized-plugin" \
          "python-slugify" \
          "mkdocs-git-committers-plugin-2" \
          "mkdocs-rss-plugin" \
          #"mkdocs-techdocs-core" \
          #"mkdocs-multirepo-plugin" \
      - run: make deploy
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}